### ISSUE TITLE
[Request]: CalDav synctonization

### ISSUE THREAD

**Issue by sim6** [dgsasha/remembrance#35]
### Tell us the problem or your need

I cannot found how to configure a CalDav server like nextcloud.

### Describe the solution you'd like

Use Gnome Online Accounts

### Describe alternatives you've considered

An option to configure CalDav service in Preferences Syncing section or some kind of documentation about how to configure CalDav service.

### Additional context

Readme says that CalDav is supported.

**Comment by dgsasha** [comment]
This is a repeat of #14, and is already coming in the next update.

GNOME online accounts will not be supported since this is not a core app and doesn't use Evolution Data Server, but you can add accounts through the preferences page.

![image](https://user-images.githubusercontent.com/86973360/235977953-491737c4-6d75-48f5-9b1c-6fe352f1a942.png)

**Comment by sim6** [comment]
Ops. Thanks! Apologies for the noise.
